<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1 (Total recall)

|Term|Brief description|
|:-|:-|
|Subsetting|Select a subset of the data in a list (or array)|
|Indexing|Select a single element|
|Slicing|Select a range of elements|
|Masking|Subset numbers in an array to show only those that are True|

# Exercise 2 (Show me the 'odd' letters)

In [44]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

## 1. Subset all the first elements.

In [31]:
subset_numbers=np_array_2d[:,0]
subset_numbers

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

## 2. Convert this to integers using astype(int)

In [30]:
convert_string_to_int=subset_numbers.astype(int)
convert_string_to_int

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

## 3. Use % to get the remainder for division by 2.

In [29]:
remainder_divide_2=convert_string_to_int%2
remainder_divide_2

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

## 4. Use the previous result to create a mask that checks if the remainder is zero or not

In [32]:
my_mask=remainder_divide_2==True
my_mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

## 5. Use the mask and extract the corresponding second elements.

In [46]:
np_array_2d[my_mask,1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

# Exercise 3

In [71]:
py_list_2d=[[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]
np_array_2d=np.array(py_list_2d)

In [72]:
np_array_2d.astype(int)

array([[66, 50, 57, -1, -1],
       [92, -1, 88, -1, -1],
       [75, -1, -1, 76, -1],
       [-1, 51, 87, -1, -1],
       [71, -1, 67, -1, 69]])

In [73]:
np_array_2d[np_array_2d<50]=-1
np_array_2d[np_array_2d>50]=+1
np_array_2d[np_array_2d==50]=0
print(np_array_2d)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
