<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [2]:
import numpy as np

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

**Python Lists**

In [1]:
py_super_names=['Black Widow','Iron Man','Doctor Strange']
py_real_names=['Natasha Romanoff','Tony Stark','Stephen Strange']

**Numpy Arrays**

In [4]:
import numpy as np
np_super_names=np.array(['Black Widow','Iron Man','Doctor Strange'])
np_real_names=np.array(['Natasha Romanoff','Tony Stark','Stephen Strange'])

**Dictionary**

In [6]:
superhero_info={'Natasha Romanoff':'Black Widow',
               'Tony Stark':'Iron Man',
               'Stephen Strange':'Doctor Strange'}

## 1.2 Accessing data from a list (or array)

In [7]:
py_real_names[0]

'Natasha Romanoff'

In [8]:
py_super_names[0]

'Black Widow'

In [9]:
py_super_names[2]

'Doctor Strange'

In [10]:
py_super_names[-1]

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [11]:
superhero_info['Natasha Romanoff']

'Black Widow'

In [12]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [13]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [14]:
py_superhero_info=[['Natasha Romanoff','Black Widow'],
                   ['Tony Stark','Iron Man'],
                   ['Stephen Strange','Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [17]:
py_list_2d=[[1,'A'],
            [2,'B'],
            [3,'C'],
            [4,'D'],
            [5,'E'],
            [6,'F'],
            [7,'G'],
            [8,'H'],
            [9,'I'],
            [10,'J']]

np_array_2d=np.array(py_list_2d)

In [20]:
len(py_list_2d)


10

In [21]:
len(np_array_2d)


10

In [22]:
np_array_2d.shape

(10, 2)

## 2.2 Arrays are fussy about type

In [23]:
py_list=[1,1.5,'A']
np_array=np.array(py_list)

In [24]:
py_list

[1, 1.5, 'A']

In [25]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [26]:
py_list=[1,2,3,4,5]
np_array=np.array(py_list)

In [27]:
np_array+10

array([11, 12, 13, 14, 15])

In [30]:
py_list+10

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [31]:
py_list_1=[1,2,3,4,5]
py_list_2=[10,20,30,40,50]

np_array_1=np.array(py_list_1)
np_array_2=np.array(py_list_2)

In [32]:
py_list_1+py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [33]:
np_array_1+np_array_2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [34]:
py_list=[1,2,3,4,5]
np_array=np.array(py_list)

In [35]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [36]:
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [37]:
py_list=[1,2,3,4,5]
np_array=np.array(py_list)

In [38]:
np_array**2

array([ 1,  4,  9, 16, 25])

In [39]:
py_list**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## 2.7 Asking questions

In [40]:
py_list=[1,2,3,4,5]
np_array=np.array(py_list)

In [41]:
py_list==3

False

In [42]:
np_array==3

array([False, False,  True, False, False])

In [43]:
np_array>3

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [44]:
py_list=[1,2,3,4,5]
np_array=np.array(py_list)

In [45]:
sum(py_list)

15

In [46]:
max(py_list)

5

In [47]:
min(py_list)

1

In [50]:
py_list.sum()

AttributeError: 'list' object has no attribute 'sum'

In [51]:
np_array.sum()

np.int64(15)

In [52]:
np_array.max()

np.int64(5)

In [53]:
np_array.min()

np.int64(1)

In [54]:
np_array.mean()

np.float64(3.0)

In [55]:
np_array.std()

np.float64(1.4142135623730951)

## Footnotes

In [5]:
x=100
f'This is an English sentence {x:^5d}'

'This is an English sentence  100 '

In [6]:
f'hehe {x:5d}'

'hehe   100'

In [7]:
f'hehe {x:5f}'

'hehe 100.000000'

In [9]:
f'hehe{x:.5f}'

'hehe100.00000'

In [11]:
f'hehe{x:.5d}'

ValueError: Precision not allowed in integer format specifier

In [13]:
py_list=[1,2,3,4,5]
import numpy as np
np_array=np.array(py_list)
np_array

array([1, 2, 3, 4, 5])

In [14]:
py_list+1

TypeError: can only concatenate list (not "int") to list

In [15]:
py_list+[1]

[1, 2, 3, 4, 5, 1]

In [16]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [17]:
np_array*2

array([ 2,  4,  6,  8, 10])

In [18]:
py_list**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [19]:
np_array**2

array([ 1,  4,  9, 16, 25])

In [20]:
py_list

[1, 2, 3, 4, 5]

In [21]:
np_array

array([1, 2, 3, 4, 5])

In [22]:
py_list=py_list*2
py_list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [34]:
py_list*2

[1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,


In [35]:
py_list*2

[1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,


In [38]:
py_list=[1,2,3,4,5]
py_list

[1, 2, 3, 4, 5]

In [39]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [40]:
len(py_list)

5

In [41]:
len(np_array)

5

In [42]:
np_array.size

5

In [43]:
np_array.shape

(5,)

In [44]:
py_list=[1,2,3,4,5]
import numpy as np
np_array=np.array(py_list)
np_array.shape

(5,)

In [60]:
my_numbers=np.random.randint()
my_numbers

TypeError: randint() takes at least 1 positional argument (0 given)