<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [5]:
py_list=['a1','b2','c3','d4','e5','f6','g7','h8','i9','j10']
np_array=np.array(py_list)
x=py_list

In [6]:
x[0]

'a1'

In [7]:
x[-1]

'j10'

In [8]:
x[0:3]

['a1', 'b2', 'c3']

In [9]:
x[1:6]

['b2', 'c3', 'd4', 'e5', 'f6']

In [10]:
x[1:6:2]

['b2', 'd4', 'f6']

In [11]:
x[5:]

['f6', 'g7', 'h8', 'i9', 'j10']

In [12]:
x[:5]

['a1', 'b2', 'c3', 'd4', 'e5']

In [13]:
x[::-1]

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

## 1.2 Arrays only | Subsetting by masking

In [14]:
np_array=np.array([1,2,3,4,5,6,7,8,9,10])
my_mask=np_array>3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [15]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [16]:
np_array[np_array>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [17]:
np_array[~(np_array>3)]

array([1, 2, 3])

In [18]:
np_array[(np_array>3)&(np_array<8)]

array([4, 5, 6, 7])

In [19]:
np_array[(np_array<3)|(np_array>8)]

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [21]:
py_list_2d=[[1,'A'],
           [2,'B'],
           [3,'C'],
            [4,'D'],
            [5,'E'],
            [6,'F'],
            [7,'G'],
            [8,'H'],
            [9,'I'],
            [10,'J']]

np_array_2d=np.array(py_list_2d)

In [22]:
py_list_2d[3]

[4, 'D']

In [24]:
np_array_2d[3]

array(['4', 'D'], dtype='<U21')

In [25]:
py_list_2d[3][0]

4

In [26]:
np_array_2d[3,0]

np.str_('4')

In [27]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [28]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [29]:
py_list_2d[:3][0]

[1, 'A']

In [30]:
np_array_2d[:3,0]

array(['1', '2', '3'], dtype='<U21')

In [31]:
py_list_2d[3:6][0]

[4, 'D']

In [32]:
np_array_2d[3:6,0]

array(['4', '5', '6'], dtype='<U21')

In [33]:
np_array_2d[:,0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

In [34]:
x=[1,2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [3]:
%%timeit x=[1]
x=x+[2]
x=x+[3]
x=x+[4]
x

79.5 μs ± 6.44 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [4]:
%%timeit x=[1]
x+=[2]
x+=[3]
x+=[4]
x

396 ns ± 16.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [5]:
%%timeit x=[1]
x.append(2)
x.append(3)
x.append(4)
x

219 ns ± 7.65 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [6]:
x=[1,2,3]
x+=[4,5,6]
x

[1, 2, 3, 4, 5, 6]

In [43]:
x=[1,2,3]
x.extend([4,5,6])
x

[1, 2, 3, 4, 5, 6]

In [44]:
x=[1,2,3]
x.append([4,5,6])
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [45]:
a=(1,2,3)

In [46]:
print(a[0])

1


In [48]:
a[0]=-1


TypeError: 'tuple' object does not support item assignment

In [49]:
a[0]+=[10]

TypeError: unsupported operand type(s) for +=: 'int' and 'list'

## 1.6 Be VERY careful when copying

In [52]:
x=[1,2,3]
y=x
z=x

In [53]:
print(x)

[1, 2, 3]


In [54]:
print(y)

[1, 2, 3]


In [55]:
print(z)

[1, 2, 3]


In [57]:
x=[1,2,3]
y=x.copy()
z=x.copy()

In [58]:
print(y)

[1, 2, 3]


In [59]:
print(z)

[1, 2, 3]


In [60]:
x=[1,[2,3]]
y=x.copy()
y[1].append(4)
print(x)

[1, [2, 3, 4]]


In [61]:
print(y)

[1, [2, 3, 4]]


## Footnotes